{
  "hash": "2be7c9de07c3737e7b22e438bb305244",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Minggu 07: Variabel Acak Kontinu\"\nsubtitle: \"Normal Distribution, Exponential Distribution\"\n---\n\n![“Lampu rata-rata hidup 900 jam, simpangan 50 jam. Kamu mau kasih garansi 700 jam, 800 jam, atau 900 jam? Ini bukan sekadar ‘baik hati’—ini strategi biaya klaim. Normal sering muncul di data pengukuran; eksponensial sering muncul di waktu tunggu. Hari ini kamu belajar menghitung peluang rusak sebelum waktu T, lalu menentukan T yang masuk akal untuk target klaim. Kamu akan melihat: statistik bisa jadi alat desain produk.”](../The_Decision_Engineer.png/image7.png)\n\n\n## 1. Konsep Pengetahuan\nDistribusi Normal (kurva lonceng) untuk data pengukuran alami, Distribusi Eksponensial untuk waktu tunggu antar kejadian.\n\n## 2. Tipikal Problem\nMenentukan garansi produk lampu. Diketahui masa hidup lampu berdistribusi Normal dengan rata-rata 900 jam dan standar deviasi 50 jam.\n\n## 3. Solusi & Pengambilan Keputusan\nMenghitung peluang lampu mati sebelum waktu tertentu (misal P(X < 700)). Perusahaan menetapkan masa garansi di titik di mana hanya sebagian kecil (misal 1%) lampu yang akan rusak, untuk meminimalkan biaya penggantian klaim garansi.\n\n## 4. Eksplorasi Komputasi (Python)\n\n\n## Live Coding: \"Normal is Everywhere\"\n\nMisalnya suatu pabrik bisa menghasilkan 10000 lampu pertahun yang bisa bekerja rata-rata 900 jam, meskipun dalam kenyataanya kapan individual lampu bisa mati bervariasi. Seberapa besar variasi ini diukur oleh besaran deviasi, misalnya deviasi 50 jam yang berarti variance 2500 jam^2.\n\nUntuk menang bersaing, harga harus murah dan garansi harus panjang. Bila ongkos produksi perlampu $5, biaya penggantian (termasuk produksi dan pengiriman) $7 per lampu yang rusak dalam mas garansi. Supaya untung paling besar mau dijual berapa dan garansi berapa lama? Misalnya pilihan harga [$12, $13.5, atau $15]. Pilihan garansi [750 jam, 800 jam, 850 jam]. Maka profit dihitung dari jumlah yang laku, harga, biaya produksi, jumlah yang rusak, dan kewajiban garansi. \n\nAda sebuah random variable di sini: X = usia lampu, sehingga E(X) = 900 jam. Kita ingin tahu berapa peluang P[X < T] jumlah unit yang harus diganti karena usia lampu tidak berhasil mencapai batas garansi w.\n\nKita misalnya mengukur usia lampu di laboratorium dan kita menemukan distribusi kumulatif menurut tabel ini:\n\n::: {#tab-rvk-tabel}\n| durasi | kumulatif|\n|--------|----------|\n| 500    | 0.05     |\n| 600    | 0.10     |\n| 700    | 0.20     |\n| 800    | 0.3      |\n| 900    | 0.34     |\n| 1000   | 0.55     |\n| 1100   | 0.7      |\n| 1200   | 1.0      |\n\nTabel hasil pengukuran durasi lampu disajikan secara kumulatif\n:::\n\nBagaimana memodelkan pengaruh harga dan garansi terhadap profit? Untuk praktik, saya sarankan:\n\n- pakai **profit per unit ekspektasian**: $p-c-gF(w)$\n\n- pakai **market share logit sederhana**: $s(p,w)=\\frac{e^{-bp+dw}}{e^{-bp+dw}+K}$\n\n- maksimalkan: $\\Pi(p,w)=M,s(p,w),[p-c-gF(w)]$\n\nKarena model ini:\n\n- sederhana\n- masuk akal\n- mudah dikalibrasi dari data pasar\n- mudah disimulasikan\n\nKode menjadi:\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport math\n\nM = 100000\nc = 5\ng = 10\nprices = [12, 13.5, 15]\nwarranties = [8000, 9000]\n\n\ndef market_share(p, w):\n    A = math.exp(-0.25 * p + 0.00015 * w)\n    return A / (A + 1.5)\n\ndef F_uniform(w):\n    A=0\n    B=20000\n    return (w-A)/(B-A)\n\ndef F_normal(w):\n    z = (w - 10000) / 1000\n    return 0.5 * (1 + math.erf(z / math.sqrt(2)))\n\n\ndef F_exponential(w):\n    return 1 - math.exp(-0.00005 * w)\n\n\ndef F_weibull(w, k=2, eta=11000):\n    return 1 - math.exp(- (w / eta) ** k)\n\n\ndef profit_per_unit(p, w, F):\n    return p - c - g * F(w)\n\n\ndef total_profit(p, w, F):\n    return M * market_share(p, w) * profit_per_unit(p, w, F)\n\n\nmodels = {\n    \"Uniform\":F_uniform,\n    \"Normal\": F_normal,\n    \"Eksponensial\": F_exponential,\n    \"Weibull\": F_weibull,\n}\n\nfor name, F in models.items():\n    print(f\"\\n=== {name} ===\")\n    best = None\n    for p in prices:\n        for w in warranties:\n            claim = F(w)\n            share = market_share(p, w)\n            unit_profit = profit_per_unit(p, w, F)\n            total = total_profit(p, w, F)\n            print(\n                f\"p={p:>4}, w={w:>4}, F={claim:.4f}, share={share:.4f}, \"\n                f\"pi={unit_profit:.4f}, Pi={total:,.2f}\"\n            )\n            if best is None or total > best[-1]:\n                best = (p, w, total)\n    print(f\"Best: price={best[0]}, warranty={best[1]}, total profit={best[2]:,.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== Uniform ===\np=  12, w=8000, F=0.4000, share=0.0993, pi=3.0000, Pi=29,778.24\np=  12, w=9000, F=0.4500, share=0.1135, pi=2.5000, Pi=28,375.33\np=13.5, w=8000, F=0.4000, share=0.0704, pi=4.5000, Pi=31,682.83\np=13.5, w=9000, F=0.4500, share=0.0809, pi=4.0000, Pi=32,351.55\np=  15, w=8000, F=0.4000, share=0.0495, pi=6.0000, Pi=29,687.31\np=  15, w=9000, F=0.4500, share=0.0570, pi=5.5000, Pi=31,366.26\nBest: price=13.5, warranty=9000, total profit=32,351.55\n\n=== Normal ===\np=  12, w=8000, F=0.0228, share=0.0993, pi=6.7725, Pi=67,224.36\np=  12, w=9000, F=0.1587, share=0.1135, pi=5.4134, Pi=61,443.35\np=13.5, w=8000, F=0.0228, share=0.0704, pi=8.2725, Pi=58,243.59\np=13.5, w=9000, F=0.1587, share=0.0809, pi=6.9134, Pi=55,915.19\np=  15, w=8000, F=0.0228, share=0.0495, pi=9.7725, Pi=48,353.20\np=  15, w=9000, F=0.1587, share=0.0570, pi=8.4134, Pi=47,981.53\nBest: price=12, warranty=8000, total profit=67,224.36\n\n=== Eksponensial ===\np=  12, w=8000, F=0.3297, share=0.0993, pi=3.7032, Pi=36,758.26\np=  12, w=9000, F=0.3624, share=0.1135, pi=3.3763, Pi=38,321.24\np=13.5, w=8000, F=0.3297, share=0.0704, pi=5.2032, Pi=36,633.80\np=13.5, w=9000, F=0.3624, share=0.0809, pi=4.8763, Pi=39,438.82\np=  15, w=8000, F=0.3297, share=0.0495, pi=6.7032, Pi=33,166.66\np=  15, w=9000, F=0.3624, share=0.0570, pi=6.3763, Pi=36,363.66\nBest: price=13.5, warranty=9000, total profit=39,438.82\n\n=== Weibull ===\np=  12, w=8000, F=0.4108, share=0.0993, pi=2.8924, Pi=28,709.96\np=  12, w=9000, F=0.4880, share=0.1135, pi=2.1200, Pi=24,062.81\np=13.5, w=8000, F=0.4108, share=0.0704, pi=4.3924, Pi=30,925.09\np=13.5, w=9000, F=0.4880, share=0.0809, pi=3.6200, Pi=29,278.54\np=  15, w=8000, F=0.4108, share=0.0495, pi=5.8924, Pi=29,154.80\np=  15, w=9000, F=0.4880, share=0.0570, pi=5.1200, Pi=29,199.41\nBest: price=13.5, warranty=8000, total profit=30,925.09\n```\n:::\n:::\n\n\nWeek 07: Distribusi Kontinu: Kurva Normal dan Eksponensial dalam Rekayasa\n\n## Agenda Perkuliahan Minggu 7\n**Tema Misi:** \"Predicting the Unpredictable: From Bell Curves to Waiting Games\"\n\n### Pertemuan 1: Senin (1 Jam) - The Intuition & The Bell Curve\n**Fokus:** Memahami mengapa Distribusi Normal adalah \"raja\" distribusi dan kapan menggunakan Eksponensial untuk waktu.\n\n- **00:00 - 00:10 | The Hook: \"Misteri Tinggi Badan & Error GPS\"**\n    - Aktivitas: Tampilkan histogram data tinggi badan 10.000 orang (atau data error GPS). Bentuknya selalu lonceng simetris.\n    - Pertanyaan: \"Kenapa fenomena yang tampak acak ini selalu membentuk pola yang sama? Kenapa tidak kotak atau segitiga?\"\n    - Konsep: Perkenalkan Distribusi Normal (Gaussian) sebagai hasil akumulasi banyak faktor kecil (prekursor Teorema Limit Pusat).\n\n- **00:10 - 00:30 | Live Coding: \"Normal is Everywhere\"**\n    - Dosen (Python Demo):\n        1. Generate data acak `numpy.random.normal`.\n        2. Tunjukkan aturan empiris: 68% data ada di $\\mu \\pm \\sigma$, 95% di $\\mu \\pm 2\\sigma$.\n        3. Visualisasi: Plot kurva lonceng dengan seaborn dan arsir area probabilitas.\n\n- **00:30 - 00:50 | Deep Dive: Menunggu Bus (Eksponensial)**\n    - Skenario: \"Kamu menunggu bus. Sudah 10 menit berlalu. Apakah peluang bus datang 5 menit lagi jadi lebih besar?\"\n    - Konsep: Perkenalkan Distribusi Eksponensial dan sifat *Memoryless*. Jika bus datang secara acak (Poisson), waktu tunggunya tidak peduli masa lalu.\n\n- **00:50 - 01:00 | Pod Formation & Mission Brief**\n    - Misi GitHub: \"The Warranty Game\". Mahasiswa harus menentukan masa garansi produk agar perusahaan tidak rugi bandar.\n\n### Pertemuan 2: Rabu (2 Jam) - Simulation Lab\n**Fokus:** Menggunakan Python untuk analisis reliabilitas produk dan menghitung probabilitas 'ekor' (*tail events*).\n\n- **00:00 - 00:20 | Setup & Micro-Lecture: PDF vs Probabilitas**\n    - Konsep: Ingatkan bahwa untuk kontinu, $P(X=x)=0$. Probabilitas adalah Luas Area ($P(a < X < b)$).\n    - Python Tool: `scipy.stats.norm.cdf` (Cumulative Distribution Function) adalah teman terbaik kita.\n\n- **00:20 - 01:10 | Pod Challenge: \"Product Reliability Engineer\"**\n    - Skenario: Anda Insinyur Kualitas di pabrik SSD (Solid State Drive).\n    - Data: Umur SSD berdistribusi Normal ($\\mu=5$ tahun, $\\sigma=1$ tahun).\n    - Tugas (Python):\n        1. Hitung berapa persen SSD yang rusak sebelum 3 tahun.\n        2. Tentukan masa garansi (dalam tahun) agar klaim garansi maksimal hanya 1% dari total produksi (Cari $x$ dimana $P(X < x) = 0.01$).\n        3. Simulasi: Generate 10.000 umur SSD, hitung biaya penggantian jika garansi diset 3 tahun vs 2 tahun.\n\n- **01:10 - 01:40 | Studi Kasus: \"Latency & SLA\"**\n    - Analisis performa server. Jika latency rata-rata 200ms ($\\sigma=50$ms), berapa peluang request timeout (>350ms)? (Aplikasi Z-score).\n\n- **01:40 - 01:50 | Share & Interpretasi**\n    - Pods mempresentasikan keputusan garansi mereka.\n\n- **01:50 - 02:00 | Exit Ticket**\n    - Pertanyaan: \"Sebutkan satu kejadian di dunia nyata yang kira-kira mengikuti distribusi Normal dan satu yang Eksponensial.\"\n\n---\n\n## Materi Kuliah: Konsep, Aplikasi, & Komputasi\n\n### 1. Konsep Dasar\n- **Distribusi Normal (Gaussian):** Distribusi paling penting, berbentuk lonceng simetris. Ditentukan oleh dua parameter: Mean ($\\mu$) menentukan pusat, Standar Deviasi ($\\sigma$) menentukan lebar/sebaran.\n    - **Standard Normal (Z):** Distribusi normal dengan $\\mu=0, \\sigma=1$.\n- **Distribusi Eksponensial:** Memodelkan waktu tunggu antar kejadian dalam proses Poisson. Parameter $\\lambda$ (laju kejadian).\n    - **Sifat Memoryless:** $P(X > t+s | X > t) = P(X > s)$. Sejarah tidak mempengaruhi masa depan.\n- **Probabilitas Kontinu:** Peluang pada satu titik spesifik adalah nol. Peluang dihitung sebagai integral dari fungsi kepadatan peluang (PDF).\n\n### 2. Aplikasi Sistem Informasi\n- **SLA (Service Level Agreement):** Menjamin bahwa \"99% request akan selesai dalam < 300ms\". Ini menggunakan perhitungan ekor distribusi Normal/Log-Normal.\n- **MTTF (Mean Time To Failure):** Memodelkan umur komponen perangkat keras (hard disk, server) menggunakan distribusi Eksponensial untuk perencanaan maintenance.\n- **Anomaly Detection:** Menggunakan skor-Z. Jika data poin memiliki $|Z| > 3$ (jauh dari rata-rata), itu dicurigai sebagai anomali atau serangan siber.\n\n### 3. Komputasi (Python)\n- **Scipy Stats:**\n    - `norm.pdf(x, loc, scale)`: Tinggi kurva.\n    - `norm.cdf(x, loc, scale)`: Luas area di kiri $x$ (Probabilitas kumulatif).\n    - `norm.ppf(q, loc, scale)`: Kebalikan CDF (Mencari nilai $x$ dari persentase).\n- **Visualisasi:** Menggunakan `seaborn.kdeplot` untuk melihat apakah data empiris mendekati bentuk lonceng.\n\n---\n\n## Tugas Kelompok (GitHub Classroom)\n**Judul:** Week 7: The Guarantee Gambler - Optimizing Warranty Risks\n\n**Deskripsi:**\nMahasiswa berperan sebagai tim Analis Risiko untuk peluncuran Smart Lamp baru. Mereka harus menyeimbangkan antara daya tarik marketing (garansi lama) dan risiko kebangkrutan (klaim garansi meledak).\n\n**Set Soal (Notebook):**\n1. **Analisis Normal (30 poin):**\n    - Diketahui umur lampu $N(\\mu=10.000 \\text{ jam}, \\sigma=1.000 \\text{ jam})$.\n    - Hitung probabilitas lampu mati sebelum 8.000 jam.\n    - Cari \"titik aman\" jam ke berapa sehingga 95% lampu masih hidup.\n2. **Analisis Eksponensial (30 poin):**\n    - Modul Wi-Fi pada lampu memiliki laju kegagalan $\\lambda=0.00005$ per jam.\n    - Hitung probabilitas modul ini bertahan lebih dari 20.000 jam.\n    - Buktikan sifat *memoryless* dengan simulasi: Bandingkan peluang bertahan 1000 jam lagi untuk modul baru vs modul yang sudah nyala 5000 jam.\n3. **Keputusan Bisnis (40 poin):**\n    - Biaya produksi = $5. Harga jual = $15. Biaya ganti rugi garansi = $10 (rugi total).\n    - Simulasikan profit total untuk 10.000 unit dengan opsi Garansi A (9.000 jam) vs Garansi B (8.000 jam).\n    - Buat rekomendasi: Mana yang memberikan profit bersih terbesar?\n\n---\n\n## 15 Soal & Solusi\n\n### A. Pertanyaan Konseptual\n\n1. **Soal:** Mengapa probabilitas $P(X=x)$ pada distribusi kontinu selalu bernilai nol?\n   - **Solusi:** Karena pada distribusi kontinu, probabilitas didefinisikan sebagai luas area di bawah kurva PDF. Untuk satu titik tunggal (garis vertikal), lebarnya adalah nol, sehingga luas areanya (integral dari $x$ ke $x$) adalah nol. Probabilitas hanya bermakna dalam interval $P(a < X < b)$.\n\n2. **Soal:** Jelaskan makna fisis dari parameter $\\mu$ dan $\\sigma$ pada kurva lonceng distribusi Normal.\n   - **Solusi:**\n     - $\\mu$ (Mean): Menunjukkan lokasi pusat atau puncak dari kurva lonceng (nilai yang paling mungkin muncul).\n     - $\\sigma$ (Standar Deviasi): Menunjukkan seberapa lebar atau gemuk kurva tersebut. $\\sigma$ besar berarti kurva landai (data menyebar), $\\sigma$ kecil berarti kurva lancip (data terpusat di sekitar mean).\n\n3. **Soal:** Apa itu skor-Z dan mengapa kita perlu menstandarisasi variabel acak Normal?\n   - **Solusi:** Skor-Z ($z=(x-\\mu)/\\sigma$) mengukur berapa standar deviasi suatu nilai data berada dari rata-ratanya. Kita menstandarisasi variabel ke Normal Standar ($Z \\sim N(0,1)$) agar bisa membandingkan data dari distribusi yang berbeda (misal: membandingkan nilai ujian Matematika dan Fisika) dan menggunakan tabel probabilitas standar.\n\n4. **Soal:** Jelaskan sifat memoryless (tidak memiliki memori) pada distribusi Eksponensial dalam konteks kegagalan komponen.\n   - **Solusi:** Sifat memoryless berarti peluang komponen akan rusak dalam $t$ jam ke depan tidak dipengaruhi oleh sudah berapa lama komponen itu bekerja. Komponen bekas (yang masih berfungsi) dianggap memiliki reliabilitas yang sama dengan komponen baru. $P(X > t+s | X > s) = P(X > t)$.\n\n5. **Soal:** Bagaimana hubungan antara distribusi Normal dan Teorema Limit Pusat secara intuitif?\n   - **Solusi:** Teorema Limit Pusat (CLT) menyatakan bahwa jika kita menjumlahkan banyak variabel acak independen (apa pun distribusi aslinya), hasil penjumlahannya akan cenderung berdistribusi Normal. Ini menjelaskan mengapa distribusi Normal muncul di mana-mana di alam (seperti tinggi badan), karena fenomena tersebut adalah hasil akumulasi dari banyak faktor genetik dan lingkungan yang kecil-kecil.\n\n### B. Pertanyaan Aplikatif\n\n6. **Soal:** Waktu respons server berdistribusi Normal dengan mean 200ms dan standar deviasi 50ms. Berapa persen respons yang memakan waktu lebih dari 300ms?\n   - **Solusi:** Hitung skor-Z: $Z=(300-200)/50=2$. Cari peluang $P(Z > 2)$. Dari tabel/rumus, $P(Z < 2) \\approx 0.9772$. Maka $P(X > 300) = 1 - 0.9772 = 0.0228$ atau 2.28%.\n\n7. **Soal:** Umur pakai sebuah baterai laptop berdistribusi Eksponensial dengan rata-rata 5 tahun. Berapa probabilitas baterai bertahan lebih dari 8 tahun?\n   - **Solusi:** Rata-rata ($\\mu$) = $1/\\lambda=5 \\rightarrow \\lambda=0.2$. Fungsi reliabilitas (survival): $P(X > x) = e^{-\\lambda x}$. $P(X > 8) = e^{-0.2 \\times 8} = e^{-1.6} \\approx 0.2019$ atau 20.19%.\n\n8. **Soal:** Skor ujian masuk sebuah universitas berdistribusi Normal dengan rata-rata 500 dan simpangan baku 100. Jika diambil 10% terbaik, berapakah skor minimumnya?\n   - **Solusi:** Kita mencari nilai $x$ dimana $P(X > x) = 0.10$, atau $P(X < x) = 0.90$. Dari tabel Z invers, nilai Z untuk area 0.90 adalah $\\approx 1.28$. $x = \\mu + Z\\sigma = 500 + (1.28 \\times 100) = 628$. Skor minimum 628.\n\n9. **Soal:** Analisis lebar pita (bandwidth) yang digunakan oleh user di mana penggunaan rata-rata adalah 10 Mbps dengan distribusi Normal.\n   - **Solusi:** Karena bandwidth tidak bisa negatif, distribusi Normal murni mungkin kurang tepat jika $\\sigma$ besar (karena ekor kiri bisa masuk area negatif). Namun, sebagai pendekatan, kita bisa menghitung peluang penggunaan melebihi kapasitas tertentu (misal 15 Mbps) untuk capacity planning.\n\n10. **Soal:** Gunakan distribusi Eksponensial untuk memodelkan waktu antar-kedatangan (inter-arrival time) permintaan ke server web.\n    - **Solusi:** Jika server menerima rata-rata 5 request per detik ($\\lambda=5$), maka waktu antar-kedatangan mengikuti Exp(5). Rata-rata waktu tunggu antar request adalah $1/5=0.2$ detik. Probabilitas menunggu lebih dari 1 detik sangat kecil: $e^{-5(1)} = 0.0067$.\n\n### C. Pertanyaan Komputasional\n\n11. **Soal:** Gunakan `scipy.stats.norm.cdf` untuk menghitung probabilitas di antara dua nilai pada distribusi Normal.\n    - **Solusi:**\n```python\nfrom scipy.stats import norm  \nmu, sigma = 100, 15  \n# P(85 < X < 115)  \nprob = norm.cdf(115, mu, sigma) - norm.cdf(85, mu, sigma)  \nprint(f\"Probabilitas: {prob:.4f}\")  \n```\n\n12. **Soal:** Tulis skrip Python untuk menghasilkan plot distribusi Normal Standar dan arsirlah area di bawah kurva untuk $P(-1 < Z < 1)$.\n    - **Solusi:**\n```python\nimport numpy as np; import matplotlib.pyplot as plt  \nfrom scipy.stats import norm  \nx = np.linspace(-3, 3, 100)  \nplt.plot(x, norm.pdf(x))  \nx_fill = np.linspace(-1, 1, 100)  \nplt.fill_between(x_fill, norm.pdf(x_fill), alpha=0.5)  \nplt.show()  \n```\n\n13. **Soal:** Implementasikan fungsi untuk menghitung skor-Z dari sekumpulan data numerik menggunakan numpy.\n    - **Solusi:**\n```python\nimport numpy as np  \ndef calculate_z_scores(data):  \n    return (data - np.mean(data)) / np.std(data)  \ndata = [1, 2, 3, 4, 5]  \nprint(calculate_z_scores(data))  \n```\n\n14. **Soal:** Buat simulasi untuk membuktikan sifat memoryless dari distribusi Eksponensial dengan membangkitkan data acak.\n    - **Solusi:**\n```python\nfrom scipy.stats import expon  \ndata = expon.rvs(scale=10, size=10000) # Mean=10  \n# Peluang X > 15  \np_tot = len(data[data > 15]) / len(data)  \n# Peluang X > 15 GIVEN X > 5 (sisa 10)  \nsubset = data[data > 5]  \np_cond = len(subset[subset > 15]) / len(subset)  \n# Bandingkan dengan P(X > 10)  \np_ref = len(data[data > 10]) / len(data)  \nprint(f\"P(X>10): {p_ref:.3f}, P(X>15|X>5): {p_cond:.3f}\")  \n```\n\n15. **Soal:** Visualisasikan bagaimana perubahan $\\sigma$ mempengaruhi \"keruncingan\" kurva Normal menggunakan matplotlib.\n    - **Solusi:**\n```python\nx = np.linspace(-10, 10, 200)  \nplt.plot(x, norm.pdf(x, 0, 1), label='Sigma=1')  \nplt.plot(x, norm.pdf(x, 0, 0.5), label='Sigma=0.5 (Lancip)')  \nplt.plot(x, norm.pdf(x, 0, 2), label='Sigma=2 (Landai)')  \nplt.legend(); plt.show()  \n```\n\n",
    "supporting": [
      "07-Variabel_Acak_Kontinu_files\\figure-typst"
    ],
    "filters": []
  }
}