project:
   type: book

book: 
  author: Armrein Z. R. Langi
  title: "Probabilitas dan Statistik Untuk Pengambilan Keputusan"
  subtitle: "Python, Teori, dan Aplikasi"
  chapters:
    - index.qmd
    
format:
  typst:
    keep-typ: true
    include-in-header: 
       - file: main.typ
    lang: id
    papersize: iso-b5
