project:
  type: book

book:
  title: "Pengambilan Keputusan Berbasis Probabilitas dan Statistika"
  subtitle: Python, Teori, dan Aplikasi
  author: "Armein Z. R. Langi"
  date: "23/03/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter07.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: id

format:
  bookly-typst:
    keep-typ: true
    papersize: "iso-b5"
    include-before-body: "cover.typ"

