project:
  type: book

book:
  title: "Pengambilan Keputusan Berbasis Probabilitas dan Statistika"
  subtitle: Python, Teori, dan Aplikasi
  author: "Armein Z. R. Langi"
  edition: "Drat 1"
  date: "23/03/2026"
  chapters:
    - index.qmd
    - ch/01-Pola_Pikir_Probabilistik_vs_Deterministik.qmd
    - ch/02-Kerangka_Probabilitas_dan_Statistik.qmd
    - ch/03-Studi_Kasus_Aplikasi_Teknik.qmd
    - ch/04-Teorema_Probabilitas_dan_Bayes.qmd
    - ch/05-Variabel_Acak.qmd
    - ch/06-Variabel_Acak_Diskrit.qmd
    - ch/07-Variabel_Acak_Kontinu.qmd
    - ch/08-Ujian_Tengah_Semester.qmd
    - ch/09-Fungsi_Variabel_Acak.qmd
    - ch/10-Distribusi_Sampling_dan_Teorema_Limit_Pusat.qmd
    - ch/11-Estimasi.qmd
    - ch/12-Pengujian_Hipotesis.qmd
    - ch/13-Regresi.qmd
    - ch/14-Studi_Kasus_Lanjutan.qmd
    - ch/15-Studi_Kasus_Lanjutan.qmd
    - ch/16-Ujian_Akhir_Semester.qmd
    - references.qmd

bibliography: references.bib
lang: id

format:
  bookly-typst:
    keep-typ: true
    papersize: "iso-b5"
    include-before-body: "cover.typ"

