---
format: 
   typst:
      keep-typst: true
---

Distribusi normal memiliki dua parameter yaiut $\mu$ daan $\sigma$.  menggunakan lbirary scipy.stats berbentuk
```{python}
import numpy as np
from scipy.stats import norm
```

```python
norm.pdf(x)
norm.cdf(x)
norm.ppf(q)
norm.pdf(x, loc, scale)
norm.cdf(x, loc, scale)
norm.ppf(q, loc, scale)

x : titik dalam rentang RV
loc: mean (default = 0)
scale : deviasi standar (defautlt = 1)
```

contoh
```{python}
std1 = norm.cdf(1) - norm.cdf(-1)
print(std1)
std2 = norm.cdf(2) - norm.cdf(-2)
print(std2)
std3 = norm.cdf(3) - norm.cdf(-3)
print(std3)
c_0_95 = norm.ppf(0.95)
c_0_99 = norm.ppf(0.99)
h_0_95 = norm.ppf((1-0.95)/2)
h_0_99 = norm.ppf((1-0.99)/2)

print(c_0_95)
print(c_0_99)
print(h_0_95)
print(h_0_99)
radius =1

```


1. **Analisis Normal (30 poin):**
    - Diketahui umur lampu $N(\mu=10.000 \text{ jam}, \sigma=1.000 \text{ jam})$.
    - Hitung probabilitas lampu mati sebelum 8.000 jam.
    - Cari "titik aman" jam ke berapa sehingga 95% lampu masih hidup.

```{python}
mu = 10000
sigma = 1000

p = norm.cdf(8000, mu, sigma)
p_aman = 0.95
titik_95 = norm.ppf(p_aman, mu, sigma)
uji = norm.cdf(titik_95, mu, sigma)

print(f" {p}, {p_aman}, {roung(titik_95)}, {uji} ")

```


2. **Analisis Eksponensial (30 poin):**
    - Modul Wi-Fi pada lampu memiliki laju kegagalan $\lambda=0.00005$ per jam.
    - Hitung probabilitas modul ini bertahan lebih dari 20.000 jam.
    - Buktikan sifat *memoryless* dengan simulasi: Bandingkan peluang bertahan 1000 jam lagi untuk modul baru vs modul yang sudah nyala 5000 jam.
3. **Keputusan Bisnis (40 poin):**
    - Biaya produksi = $5. Harga jual = $15. Biaya ganti rugi garansi = $10 (rugi total).
    - Simulasikan profit total untuk 10.000 unit dengan opsi Garansi A (9.000 jam) vs Garansi B (8.000 jam).
    - Buat rekomendasi: Mana yang memberikan profit bersih terbesar?

